<?php
declare(strict_types=1);
session_start();
date_default_timezone_set('Asia/Kuala_Lumpur');
error_reporting(E_ALL);
ini_set('display_errors','1');
require_once __DIR__.'/db.php';
require_once __DIR__ . '/cpms/includes/permission_engine.php';

const MAX_UPLOAD_BYTES = 25 * 1024 * 1024;
const MAX_IMAGE_WIDTH = 1920;
const MAX_IMAGE_HEIGHT = 1920;
const JPEG_QUALITY = 85;

function failx(string $message): never {
    http_response_code(400);
    echo '<!doctype html><html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Patrol Gagal</title><style>body{font-family:Arial;background:#f4f6f8;margin:0;color:#26323d}.box{width:min(620px,calc(100% - 24px));margin:35px auto;padding:24px;background:#fff;border-radius:14px;box-shadow:0 10px 30px rgba(0,0,0,.08)}h1{color:#9d2929}a{display:inline-block;padding:10px 14px;background:#5b3926;color:#fff;text-decoration:none;border-radius:8px;font-weight:700}</style></head><body><main class="box"><h1>Patrol gagal disimpan</h1><p>'.htmlspecialchars($message,ENT_QUOTES,'UTF-8').'</p><a href="javascript:history.back()">Kembali</a></main></body></html>';
    exit();
}
function tableExists(mysqli $c,string $t):bool{$s=$c->prepare("SELECT COUNT(*) total FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?");$s->bind_param('s',$t);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return (int)($r['total']??0)>0;}
function columnExists(mysqli $c,string $t,string $col):bool{$s=$c->prepare("SELECT COUNT(*) total FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?");$s->bind_param('ss',$t,$col);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return (int)($r['total']??0)>0;}
function getCols(mysqli $c,string $t):array{$out=[];$r=$c->query("SHOW COLUMNS FROM `$t`");if($r){while($x=$r->fetch_assoc())$out[$x['Field']]=$x;}return $out;}
function bindDyn(mysqli_stmt $s,string $types,array &$vals):void{$p=[$types];foreach($vals as &$v)$p[]=&$v;call_user_func_array([$s,'bind_param'],$p);}
function insertDyn(mysqli $c,string $t,array $data):int{$cols=array_keys($data);$sql="INSERT INTO `$t` (`".implode('`,`',$cols)."`) VALUES (".implode(',',array_fill(0,count($cols),'?')).")";$s=$c->prepare($sql);if(!$s)throw new RuntimeException("Prepare $t gagal: ".$c->error);$types='';$vals=[];foreach($data as $v){$types.=is_int($v)?'i':(is_float($v)?'d':'s');$vals[]=$v;}bindDyn($s,$types,$vals);if(!$s->execute()){ $e=$s->error;$s->close();throw new RuntimeException("Simpan $t gagal: $e");}$id=(int)$c->insert_id;$s->close();return $id;}
function updateDyn(mysqli $c,string $t,array $data,string $where,int $id):void{if(!$data)return;$sets=[];foreach(array_keys($data) as $col)$sets[]="`$col`=?";$s=$c->prepare("UPDATE `$t` SET ".implode(',',$sets)." WHERE `$where`=?");if(!$s)throw new RuntimeException("Update $t gagal disediakan: ".$c->error);$types='';$vals=[];foreach($data as $v){$types.=is_int($v)?'i':(is_float($v)?'d':'s');$vals[]=$v;}$types.='i';$vals[]=$id;bindDyn($s,$types,$vals);if(!$s->execute()){ $e=$s->error;$s->close();throw new RuntimeException("Update $t gagal: $e");}$s->close();}
function uploadErrorText(int $c,int $n):string{return match($c){UPLOAD_ERR_INI_SIZE=>"Gambar $n melebihi had server.",UPLOAD_ERR_FORM_SIZE=>"Gambar $n terlalu besar.",UPLOAD_ERR_PARTIAL=>"Gambar $n hanya dimuat naik sebahagian.",UPLOAD_ERR_NO_TMP_DIR=>'Folder sementara server tiada.',UPLOAD_ERR_CANT_WRITE=>"Server gagal simpan gambar $n.",UPLOAD_ERR_EXTENSION=>"Upload gambar $n dihentikan server.",default=>"Gambar $n gagal dimuat naik."};}
function compressImg(string $src,string $mime,string $dst):void{if(!extension_loaded('gd'))throw new RuntimeException('PHP GD tidak tersedia.');$im=match($mime){'image/jpeg'=>@imagecreatefromjpeg($src),'image/png'=>@imagecreatefrompng($src),'image/webp'=>function_exists('imagecreatefromwebp')?@imagecreatefromwebp($src):false,default=>false};if($im===false)throw new RuntimeException('Gambar tidak dapat dibaca.');$ow=imagesx($im);$oh=imagesy($im);$scale=min(MAX_IMAGE_WIDTH/max(1,$ow),MAX_IMAGE_HEIGHT/max(1,$oh),1);$nw=max(1,(int)round($ow*$scale));$nh=max(1,(int)round($oh*$scale));$out=imagecreatetruecolor($nw,$nh);$white=imagecolorallocate($out,255,255,255);imagefill($out,0,0,$white);imagecopyresampled($out,$im,0,0,0,0,$nw,$nh,$ow,$oh);$ok=imagejpeg($out,$dst,JPEG_QUALITY);imagedestroy($im);imagedestroy($out);if(!$ok)throw new RuntimeException('Gambar gagal disimpan.');}
function woRef(mysqli $c):string{for($i=0;$i<10;$i++){$ref='WO-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$s=$c->prepare('SELECT id FROM work_orders WHERE work_order_reference=? LIMIT 1');$s->bind_param('s',$ref);$s->execute();$x=$s->get_result()->fetch_assoc();$s->close();if(!$x)return $ref;}throw new RuntimeException('Nombor Work Order unik gagal dijana.');}
function propertyId(mysqli $c,int $guard):int{if(isset($_SESSION["cpms_property_id"])&&(int)$_SESSION["cpms_property_id"]>0)return (int)$_SESSION["cpms_property_id"];if(isset($_SESSION["security_guard_property_id"])&&(int)$_SESSION["security_guard_property_id"]>0)return (int)$_SESSION["security_guard_property_id"];if(isset($_SESSION["property_id"])&&(int)$_SESSION["property_id"]>0)return (int)$_SESSION["property_id"];if(tableExists($c,"security_guards")&&columnExists($c,"security_guards","property_id")){$s=$c->prepare("SELECT property_id FROM security_guards WHERE id=? LIMIT 1");$s->bind_param("i",$guard);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();if((int)($r["property_id"]??0)>0)return (int)$r["property_id"];}return 0;}

if(!isset($_SESSION['security_guard_id'])){header('Location: cpms/login.php');exit();}
cpmsRequire('security.patrol', $conn);
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Location: security_dashboard.php');exit();}
$st=(string)($_SESSION['security_patrol_csrf']??'');$pt=(string)($_POST['csrf_token']??'');if($st===''||!hash_equals($st,$pt))failx('Permintaan tidak sah. Buka semula borang patrol.');
$locations=$_POST['locations']??[];if(!is_array($locations))$locations=[];$locations=array_values(array_filter(array_map(fn($v)=>trim((string)$v),$locations)));if(!$locations)failx('Pilih sekurang-kurangnya satu lokasi.');
$start=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',(string)($_POST['started_at']??''));$end=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',(string)($_POST['completed_at']??''));if(!$start||!$end||$end<$start)failx('Masa patrol tidak sah.');
$files=$_FILES['patrol_photos']??[];$pl=$_POST['photo_locations']??[];$pc=$_POST['photo_captions']??[];if(!isset($files['name'])||!is_array($files['name']))failx('Tiada gambar diterima oleh server.');$uploads=[];for($i=0;$i<count($files['name']);$i++){$err=(int)($files['error'][$i]??UPLOAD_ERR_NO_FILE);if($err===UPLOAD_ERR_NO_FILE)continue;$num=$i+1;if($err!==UPLOAD_ERR_OK)failx(uploadErrorText($err,$num));$loc=trim((string)($pl[$i]??''));if($loc==='')failx("Sila pilih lokasi untuk gambar $num.");$tmp=(string)($files['tmp_name'][$i]??'');$size=(int)($files['size'][$i]??0);if($tmp===''||!is_uploaded_file($tmp))failx("Fail sementara gambar $num tidak sah.");if($size<1||$size>MAX_UPLOAD_BYTES)failx("Saiz gambar $num tidak boleh melebihi 25MB.");$uploads[]=['tmp'=>$tmp,'location'=>$loc,'caption'=>trim((string)($pc[$i]??'')),'number'=>$num];}
if(!$uploads)failx('Sila pilih sekurang-kurangnya satu gambar patrol.');if(count($uploads)>10)failx('Maksimum 10 gambar dibenarkan.');
$issueFound=(int)($_POST['issue_found']??0);$cat=trim((string)($_POST['issue_category']??''));$pri=trim((string)($_POST['issue_priority']??''));$desc=trim((string)($_POST['issue_description']??''));$woReq=(int)($_POST['work_order_required']??0);if($issueFound===1&&($cat===''||$pri===''||$desc===''))failx('Lengkapkan kategori, priority dan penerangan masalah.');if($woReq===1&&$issueFound!==1)failx('Work Order hanya boleh dijana apabila Issue Found = Ya.');
$dir=__DIR__.'/uploads/security_patrol/';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))failx('Folder uploads/security_patrol tidak dapat dicipta.');if(!is_writable($dir))failx('Folder uploads/security_patrol tidak boleh ditulis.');
$saved=[];$woReference='';$woId=0;
try{$conn->begin_transaction();$guard=(int)$_SESSION['security_guard_id'];$prop=propertyId($conn,$guard);if($prop<1)throw new RuntimeException("Property context tidak sah. Sila log masuk semula melalui Unified Login.");$patRef='SP-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$pcols=getCols($conn,'security_patrols');$pdata=['patrol_reference'=>$patRef,'guard_id'=>$guard,'patrol_date'=>$start->format('Y-m-d'),'patrol_type'=>trim((string)($_POST['patrol_type']??'Routine Patrol')),'duty_type'=>trim((string)($_POST['duty_type']??'Regular Duty')),'started_at'=>$start->format('Y-m-d H:i:s'),'completed_at'=>$end->format('Y-m-d H:i:s'),'locations_checked'=>json_encode($locations,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'patrol_notes'=>trim((string)($_POST['patrol_notes']??'')),'issue_found'=>$issueFound,'issue_category'=>$cat,'issue_priority'=>$pri,'issue_description'=>$desc,'work_order_required'=>$woReq];if(isset($pcols['property_id']))$pdata['property_id']=$prop;if(isset($pcols['patrol_status']))$pdata['patrol_status']='Submitted';$pdata=array_intersect_key($pdata,$pcols);$patrolId=insertDyn($conn,'security_patrols',$pdata);
$finfo=new finfo(FILEINFO_MIME_TYPE);$icols=getCols($conn,'security_patrol_images');foreach($uploads as $u){$mime=(string)$finfo->file($u['tmp']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))throw new RuntimeException('Format gambar '.$u['number'].' tidak sah.');$name=bin2hex(random_bytes(16)).'.jpg';$dst=$dir.$name;compressImg($u['tmp'],$mime,$dst);$saved[]=$dst;$idata=['patrol_id'=>$patrolId];foreach(['image_name','file_name','filename'] as $col){if(isset($icols[$col])){$idata[$col]=$name;break;}}foreach(['image_path','file_path','photo_path'] as $col){if(isset($icols[$col])){$idata[$col]='uploads/security_patrol/'.$name;break;}}foreach(['location_label','photo_location','location'] as $col){if(isset($icols[$col])){$idata[$col]=$u['location'];break;}}foreach(['image_caption','caption','photo_caption'] as $col){if(isset($icols[$col])){$idata[$col]=$u['caption'];break;}}insertDyn($conn,'security_patrol_images',$idata);}
if($issueFound===1&&$woReq===1){if(!tableExists($conn,'work_orders'))throw new RuntimeException('Jadual work_orders tidak ditemui.');$wcols=getCols($conn,'work_orders');$woReference=woRef($conn);$main=$locations[0]??'Security Patrol';$all=implode(', ',$locations);$wdata=['property_id'=>$prop,'work_order_reference'=>$woReference,'security_patrol_id'=>$patrolId,'title'=>'Isu Security Patrol - '.($cat!==''?$cat:'General'),'description'=>$desc."

Sumber: Security Patrol $patRef
Lokasi diperiksa: $all",'category'=>$cat,'priority'=>$pri,'block_location'=>$main,'specific_location'=>$all,'scheduled_date'=>date('Y-m-d'),'due_date'=>match(strtolower($pri)){'emergency','urgent','critical','high'=>date('Y-m-d'),'medium','normal'=>date('Y-m-d',strtotime('+3 days')),default=>date('Y-m-d',strtotime('+7 days'))},'status'=>'Open','created_by'=>'Security Patrol'];$wdata=array_intersect_key($wdata,$wcols);$woId=insertDyn($conn,'work_orders',$wdata);$upd=[];if(isset($pcols['work_order_id']))$upd['work_order_id']=$woId;if(isset($pcols['work_order_reference']))$upd['work_order_reference']=$woReference;updateDyn($conn,'security_patrols',$upd,'id',$patrolId);}
$conn->commit();$_SESSION['security_patrol_csrf']=bin2hex(random_bytes(32));$q=['created'=>$patRef];if($woId>0)$q['work_order_created']=$woReference;header('Location: security_dashboard.php?'.http_build_query($q));exit();
}catch(Throwable $e){try{$conn->rollback();}catch(Throwable){}foreach($saved as $p)if(is_file($p))@unlink($p);failx($e->getMessage());}
