<?php
declare(strict_types=1); session_start(); require_once 'db.php';
function e(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
$token=trim((string)($_GET['token']??''));if($token===''){http_response_code(404);exit('Asset QR tidak sah.');}
$s=$conn->prepare("SELECT * FROM assets WHERE public_token=? AND asset_status<>'Disposed' LIMIT 1");$s->bind_param('s',$token);$s->execute();$asset=$s->get_result()->fetch_assoc();$s->close();if(!$asset){http_response_code(404);exit('Aset tidak dijumpai.');}
if(!isset($_SESSION['staff_id'])){$_SESSION['asset_inspection_return']='staff_asset_inspection.php?token='.rawurlencode($token);header('Location: cpms/login.php');exit;}
if(!isset($_SESSION['asset_inspection_csrf']))$_SESSION['asset_inspection_csrf']=bin2hex(random_bytes(32));$csrf=$_SESSION['asset_inspection_csrf'];$conn->close();
$sets=['Lamp Post'=>['Lampu menyala','Fitting dan cover baik','Tiang tidak berkarat atau senget','Kabel tidak terdedah','Kawasan selamat'],'Water Pump'=>['Pam beroperasi normal','Tiada kebocoran','Tiada bunyi atau getaran luar biasa','Tekanan mencukupi','Auto dan manual berfungsi'],'Pump Control Panel'=>['Lampu indikator berfungsi','Contactor baik','Overload relay normal','Wiring selamat','Tiada tanda panas atau terbakar'],'Boom Gate'=>['Motor berfungsi','Sensor berfungsi','Barrier arm baik','Remote berfungsi','Manual release boleh digunakan'],'Solar CCTV'=>['Kamera berfungsi','Rakaman tersedia','Panel solar bersih','Bateri baik','Pandangan tidak terhalang'],'Water Tank'=>['Paras air normal','Tiada kebocoran','Penutup selamat','Float valve berfungsi','Tangki bersih'],'Fire Hydrant'=>['Mudah diakses','Valve baik','Tiada kebocoran','Tanda lokasi jelas','Keadaan fizikal baik'],'Fire Extinguisher'=>['Pressure gauge normal','Pin dan seal lengkap','Badan tidak berkarat','Mudah diakses','Tarikh luput sah'],'Playground'=>['Struktur kukuh','Tiada bahagian tajam','Tiada karat berbahaya','Lantai selamat','Kawasan bersih'],'Drainage'=>['Tiada sumbatan','Aliran lancar','Tiada kerosakan struktur','Tiada bau luar biasa','Kawasan bersih']];$items=$sets[(string)$asset['asset_category']]??['Keadaan fizikal baik','Aset berfungsi normal','Tiada risiko keselamatan','Kawasan bersih','Tiada tindakan segera diperlukan'];
?>
<!doctype html><html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Asset Inspection</title><link rel="stylesheet" href="css/pms.css?v=8"><link rel="stylesheet" href="css/pms_asset_qr.css?v=1">    <link rel="stylesheet" href="css/genesis_workforce_web.css?v=3.1.0">
</head><body class="pms-body"><main class="pms-main" style="max-width:900px;margin:auto"><header class="pms-topbar"><div><h1>Asset Inspection</h1><p>Lengkapkan checklist dan gambar.</p></div><div class="pms-user-chip"><?=e((string)$_SESSION['staff_name'])?></div></header><section class="inspection-asset-banner"><h2><?=e((string)$asset['asset_name'])?></h2><p>Asset Code: <strong><?=e((string)$asset['asset_code'])?></strong></p><p>Kategori: <?=e((string)$asset['asset_category'])?></p><p>Lokasi: <?=e((string)$asset['location'])?></p></section><section class="pms-card"><form action="submit_asset_inspection.php" method="post" enctype="multipart/form-data" class="pms-form-grid"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="asset_token" value="<?=e($token)?>"><div class="pms-form-group pms-form-group-full"><label>Checklist Pemeriksaan</label><div class="inspection-checklist"><?php foreach($items as $item):?><label class="inspection-check-item"><input type="checkbox" name="checklist[]" value="<?=e($item)?>"><span><?=e($item)?></span></label><?php endforeach;?></div></div><div class="pms-form-group"><label>Keadaan Keseluruhan *</label><select name="condition_result" required><option value="">-- Sila Pilih --</option><option>Good</option><option>Satisfactory</option><option>Attention Required</option><option>Critical</option></select></div><div class="pms-form-group"><label>Work Order Diperlukan?</label><select name="work_order_required"><option value="0">Tidak</option><option value="1">Ya</option></select></div><div class="pms-form-group pms-form-group-full"><label>Penemuan / Masalah</label><textarea name="findings" maxlength="3000"></textarea></div><div class="pms-form-group pms-form-group-full"><label>Tindakan Segera</label><textarea name="action_taken" maxlength="3000"></textarea></div><div class="pms-form-group pms-form-group-full"><label>Gambar Pemeriksaan *</label><input type="file" name="inspection_images[]" accept="image/jpeg,image/png,image/webp" multiple required><small>Maksimum 5 gambar, 5MB setiap satu.</small></div><div class="pms-form-group pms-form-group-full"><button class="pms-button">Hantar Pemeriksaan</button></div></form></section></main></body></html>
