<?php
declare(strict_types=1);
session_start();date_default_timezone_set('Asia/Kuala_Lumpur');
require_once __DIR__.'/db.php';require_once __DIR__.'/staff_pwa_bootstrap.php';
require_once __DIR__.'/cpms/includes/permission_engine.php';
require_once __DIR__.'/cpms/includes/preventive_maintenance_service.php';
if(empty($_SESSION['staff_id'])){header('Location: cpms/login.php');exit();}
cpmsRequire('maintenance.complete',$conn);
$userId=(int)($_SESSION['cpms_user_id']??0);$propertyId=(int)($_SESSION['cpms_property_id']??$_SESSION['staff_property_id']??0);$scheduleId=(int)($_GET['id']??$_POST['schedule_id']??0);
$stmt=$conn->prepare("SELECT * FROM cpms_pm_schedules WHERE id=? AND property_id=? AND assigned_system_user_id=? AND status='active' LIMIT 1");$stmt->bind_param('iii',$scheduleId,$propertyId,$userId);$stmt->execute();$schedule=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$schedule){http_response_code(404);exit('Maintenance schedule not found or not assigned to you.');}
$errors=[];$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!cpmsPmVerifyCsrf($_POST['csrf_token']??null))$errors[]='Security session is invalid.';
 elseif(empty($_SESSION['staff_pm_completion_token'])||empty($_POST['completion_token'])||!hash_equals((string)$_SESSION['staff_pm_completion_token'],(string)$_POST['completion_token']))$errors[]='This completion was already submitted.';
 else{unset($_SESSION['staff_pm_completion_token']);try{cpmsPmComplete($conn,$propertyId,$schedule,$_POST,$_FILES['evidence']??[],__DIR__.'/cpms/uploads/preventive_maintenance');$success='Maintenance submitted for Property Admin verification.';}catch(Throwable$e){$errors[]=$e->getMessage();}}
}
if(empty($_SESSION['staff_pm_completion_token']))$_SESSION['staff_pm_completion_token']=bin2hex(random_bytes(24));
$history=cpmsPmHistory($conn,$propertyId,$scheduleId);$branding=cpmsStaffPwaBranding($conn);
function staffPmViewE(?string$v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!DOCTYPE html><html lang="ms"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Maintenance | CPMS Staff</title><link rel="stylesheet" href="css/pms.css?v=5">
<style>.pm-wrap{max-width:900px;margin:auto;padding:22px}.pm-card{background:#fff;border:1px solid #e5ded7;border-radius:14px;padding:19px;margin:14px 0}.pm-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.pm-field.full{grid-column:1/-1}.pm-field label{display:block;font-weight:800;margin-bottom:5px}.pm-field input,.pm-field select,.pm-field textarea{width:100%;box-sizing:border-box;padding:11px;border:1px solid #d9cec6;border-radius:8px}.pm-btn{display:inline-block;border:0;background:#4a2b20;color:#fff;padding:10px 14px;border-radius:8px;text-decoration:none;font-weight:800}.pm-alert{padding:12px;border-radius:8px;background:#dcfce7;color:#166534}.pm-error{background:#fee2e2;color:#991b1b}.pm-history{padding:12px;border-bottom:1px solid #e5ded7}.pm-thumb{max-width:150px;border-radius:8px}@media(max-width:700px){.pm-wrap{padding:14px}.pm-grid{grid-template-columns:1fr}.pm-field.full{grid-column:auto}}</style>
<?php echo cpmsStaffPwaHead($branding);echo cpmsStaffPwaStyle($branding);?>    <link rel="stylesheet" href="css/genesis_workforce_web.css?v=3.1.0">
</head><body class="pms-body"><main class="pm-wrap"><a class="pm-btn" href="staff_maintenance.php">← Maintenance Saya</a><h1><?php echo staffPmViewE((string)$schedule['schedule_name']);?></h1>
<?php if($success):?><div class="pm-alert"><?php echo staffPmViewE($success);?></div><?php endif;?><?php foreach($errors as$error):?><div class="pm-alert pm-error"><?php echo staffPmViewE($error);?></div><?php endforeach;?>
<section class="pm-card"><strong><?php echo staffPmViewE((string)$schedule['asset_name']);?></strong><p>Due: <?php echo staffPmViewE((string)$schedule['next_due_date']);?> · Priority: <?php echo staffPmViewE((string)$schedule['priority']);?></p><h3>Arahan</h3><p><?php echo nl2br(staffPmViewE((string)($schedule['instructions']?:'Tiada arahan tambahan.')));?></p></section>
<section class="pm-card"><h2>Hantar Maintenance Completion</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?php echo staffPmViewE(cpmsPmCsrfToken());?>"><input type="hidden" name="completion_token" value="<?php echo staffPmViewE((string)$_SESSION['staff_pm_completion_token']);?>"><input type="hidden" name="schedule_id" value="<?php echo$scheduleId;?>"><div class="pm-grid">
<div class="pm-field"><label>Tarikh Selesai</label><input type="date" name="completed_date" value="<?php echo date('Y-m-d');?>" required></div><div class="pm-field"><label>Keputusan</label><select name="result"><option>Completed</option><option>Completed with Finding</option><option>Failed</option></select></div>
<div class="pm-field full"><label>Catatan Kerja</label><textarea name="work_notes" rows="4" required></textarea></div><div class="pm-field"><label>Meter Reading</label><input name="meter_reading"></div><div class="pm-field"><label>Actual Cost (RM)</label><input type="number" name="actual_cost" min="0" step=".01"></div><div class="pm-field"><label>Downtime (minit)</label><input type="number" name="downtime_minutes" min="0"></div><div class="pm-field"><label>Gambar Bukti</label><input type="file" name="evidence" accept="image/jpeg,image/png,image/webp" required></div><div class="pm-field full"><label>Catatan Gambar</label><input name="caption"></div></div><button class="pm-btn" id="submitPm">Hantar untuk Pengesahan</button></form></section>
<section class="pm-card"><h2>Submission History</h2><?php if(!$history):?><p>Tiada submission.</p><?php endif;?><?php foreach($history as$log):?><article class="pm-history"><strong><?php echo staffPmViewE((string)$log['completed_date']);?> · <?php echo staffPmViewE((string)$log['result']);?></strong><p><?php echo staffPmViewE((string)$log['work_notes']);?></p><p>Status: <?php echo$log['verified_at']?'Verified by '.staffPmViewE((string)$log['verified_by_name']):'Pending Verification';?></p><?php if($log['evidence_path']):?><img class="pm-thumb" src="cpms/<?php echo staffPmViewE((string)$log['evidence_path']);?>"><?php endif;?></article><?php endforeach;?></section>
</main><script>document.querySelector('form[enctype="multipart/form-data"]').addEventListener('submit',function(){var b=document.getElementById('submitPm');b.disabled=true;b.textContent='Saving...';});</script></body></html>
