<?php
declare(strict_types=1);session_start();require_once 'db.php';
function failx(string $m):void{echo '<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="css/pms.css?v=8"><body class="pms-body"><main class="pms-main" style="max-width:700px;margin:40px auto"><div class="pms-alert-error">'.htmlspecialchars($m,ENT_QUOTES,'UTF-8').'</div><a class="pms-button-secondary" href="javascript:history.back()">← Kembali</a></main></body>';exit;}
if(!isset($_SESSION['staff_id'])){header('Location: cpms/login.php');exit;}if($_SERVER['REQUEST_METHOD']!=='POST'){header('Location: staff_dashboard.php');exit;}
if(!hash_equals((string)($_SESSION['asset_inspection_csrf']??''),(string)($_POST['csrf_token']??'')))failx('Permintaan tidak sah.');
$token=trim((string)($_POST['asset_token']??''));$condition=trim((string)($_POST['condition_result']??''));$findings=trim((string)($_POST['findings']??''));$action=trim((string)($_POST['action_taken']??''));$wo=(int)($_POST['work_order_required']??0);$checklist=is_array($_POST['checklist']??null)?$_POST['checklist']:[];$allowed=['Good','Satisfactory','Attention Required','Critical'];if($token===''||!in_array($condition,$allowed,true))failx('Maklumat pemeriksaan tidak lengkap.');
$s=$conn->prepare("SELECT id FROM assets WHERE public_token=? LIMIT 1");$s->bind_param('s',$token);$s->execute();$a=$s->get_result()->fetch_assoc();$s->close();if(!$a)failx('Aset tidak dijumpai.');
$f=$_FILES['inspection_images']??null;if(!is_array($f)||!is_array($f['name']??null))failx('Gambar diperlukan.');$n=count($f['name']);if($n<1||$n>5)failx('Jumlah gambar mesti 1 hingga 5.');
$dir=__DIR__.'/uploads/asset_inspections/';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))failx('Folder gambar tidak dapat dibuat.');$paths=[];$names=[];
try{$conn->begin_transaction();do{$ref='AI-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$c=$conn->prepare("SELECT id FROM asset_inspections WHERE inspection_reference=?");$c->bind_param('s',$ref);$c->execute();$exists=$c->get_result()->num_rows>0;$c->close();}while($exists);
$allow=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];for($i=0;$i<$n;$i++){if((int)$f['error'][$i]!==UPLOAD_ERR_OK)throw new RuntimeException('Gambar gagal dimuat naik.');if((int)$f['size'][$i]>5*1024*1024)throw new RuntimeException('Gambar melebihi 5MB.');$tmp=(string)$f['tmp_name'][$i];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp);$info=@getimagesize($tmp);if(!isset($allow[$mime])||!is_array($info)||($info['mime']??'')!==$mime)throw new RuntimeException('Jenis gambar tidak sah.');$name=bin2hex(random_bytes(16)).'.'.$allow[$mime];$dest=$dir.$name;if(!move_uploaded_file($tmp,$dest))throw new RuntimeException('Gambar gagal disimpan.');$paths[]=$dest;$names[]=$name;}
$json=json_encode(array_values(array_map('strval',$checklist)),JSON_UNESCAPED_UNICODE);$assetId=(int)$a['id'];$staffId=(int)$_SESSION['staff_id'];$s=$conn->prepare("INSERT INTO asset_inspections(inspection_reference,asset_id,staff_id,inspection_date,condition_result,checklist_data,findings,action_taken,work_order_required) VALUES(?,?,?,CURDATE(),?,?,?,?,?)");$s->bind_param('siissssi',$ref,$assetId,$staffId,$condition,$json,$findings,$action,$wo);if(!$s->execute())throw new RuntimeException('Rekod gagal disimpan.');$iid=(int)$conn->insert_id;$s->close();$im=$conn->prepare("INSERT INTO asset_inspection_images(inspection_id,image_name) VALUES(?,?)");foreach($names as $name){$im->bind_param('is',$iid,$name);if(!$im->execute())throw new RuntimeException('Rekod gambar gagal disimpan.');}$im->close();$conn->commit();}catch(Throwable $e){try{$conn->rollback();}catch(Throwable $x){}foreach($paths as $p)if(is_file($p))@unlink($p);failx('Pemeriksaan tidak dapat disimpan: '.$e->getMessage());}
$conn->close();header('Location: staff_dashboard.php?inspection='.urlencode($ref));exit;
