<?php
declare(strict_types=1);
session_start();require_once 'db.php';$role=(string)($_SESSION['cpms_user_role']??'');
if($role!=='system_owner'&&!isset($_SESSION['system_owner_id'])){http_response_code(403);exit('System Owner access required.');}
$checks=[];foreach(['cpms_attendance_delegations','cpms_attendance_approval_audit'] as $table){$safe=$conn->real_escape_string($table);$r=$conn->query("SELECT COUNT(*) total FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='$safe'");$checks[$table]=$r&&(int)$r->fetch_assoc()['total']===1;}
$r=$conn->query("SELECT COUNT(*) total FROM permissions WHERE permission_code IN('attendance.admin.manage','attendance.approval.delegate','attendance.approval.audit')");$checks['permissions 3/3']=$r&&(int)$r->fetch_assoc()['total']===3;
foreach(['attendance_admin.php','attendance_delegations.php','attendance_approvals.php','attendance_approval_audit.php','cpms/includes/attendance_approval_service.php'] as $f){$checks[$f]=is_file(__DIR__.'/'.$f);}$pass=!in_array(false,$checks,true);
?>
<!doctype html><html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v3.4.10 Health | CPMS</title><style>body{font:16px Arial;background:#eef3f9;color:#10213d;padding:24px}main{max-width:850px;margin:auto}.card{background:#fff;border-radius:16px;padding:25px;margin-bottom:15px}.pass{color:#07852f}.fail{color:#b42318}table{width:100%;border-collapse:collapse}td{padding:11px;border-bottom:1px solid #e2e8f0}</style></head><body><main><section class="card"><h1>CPMS v3.4.10 — Module Health</h1><h2 class="<?=$pass?'pass':'fail'?>"><?=$pass?'PASS':'FAIL'?></h2><p><a href="attendance_admin.php">Open Attendance Administration</a></p></section><section class="card"><table><?php foreach($checks as $n=>$ok):?><tr><td><?=htmlspecialchars($n)?></td><td class="<?=$ok?'pass':'fail'?>"><?=$ok?'Ready':'Missing'?></td></tr><?php endforeach;?></table></section></main></body></html>
