<?php
declare(strict_types=1);
require_once __DIR__.'/cpms/includes/resident_session.php';cpmsResidentSessionStart();require_once __DIR__.'/db.php';require_once __DIR__.'/cpms/includes/resident_portal_service.php';
$resident=cpmsResidentRequire($conn);$id=(int)($_GET['id']??0);$pid=(int)$resident['property_id'];$rid=(int)$resident['id'];
$s=$conn->prepare("SELECT sr.*,l.complaint_reference,l.work_order_id,w.work_order_reference,w.status work_order_status FROM cpms_resident_service_requests sr LEFT JOIN cpms_resident_request_links l ON l.service_request_id=sr.id LEFT JOIN work_orders w ON w.id=l.work_order_id WHERE sr.id=? AND sr.property_id=? AND sr.resident_id=? LIMIT 1");$s->bind_param('iii',$id,$pid,$rid);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();if(!$r){http_response_code(404);exit('Permohonan tidak dijumpai.');}
$s=$conn->prepare("SELECT message,new_status,created_at FROM cpms_resident_request_updates WHERE property_id=? AND service_request_id=? AND visible_to_resident=1 ORDER BY id DESC");$s->bind_param('ii',$pid,$id);$s->execute();$updates=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();
function rqEsc($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Permohonan <?=rqEsc($r['request_reference'])?></title><link rel="stylesheet" href="resident_portal.css?v=351">    <link rel="stylesheet" href="assets/genesis/resident-genesis.css?v=4.0.0">
</head><body><header class="rp-head"><div class="rp-wrap"><h1><?=rqEsc($r['request_reference'])?></h1><p><?=rqEsc($r['subject'])?></p></div></header><main class="rp-main rp-wrap"><p><a href="resident_requests.php">← Permohonan Saya</a></p><section class="rp-card"><div class="rp-grid"><div class="rp-item"><small>Status</small><br><strong><?=rqEsc($r['status'])?></strong></div><div class="rp-item"><small>Complaint</small><br><strong><?=rqEsc($r['complaint_reference']??'-')?></strong></div><div class="rp-item"><small>Work Order</small><br><strong><?=rqEsc($r['work_order_reference']??'-')?></strong></div><div class="rp-item"><small>Status Kerja</small><br><strong><?=rqEsc($r['work_order_status']??'-')?></strong></div></div><p><?=nl2br(rqEsc($r['description']))?></p></section><section class="rp-card"><h2>Kemas Kini Pengurusan</h2><div class="rp-list"><?php if(!$updates):?><div class="rp-item">Belum ada kemas kini.</div><?php endif;foreach($updates as $u):?><div class="rp-item"><strong><?=rqEsc($u['message'])?></strong><br><small class="rp-muted"><?=rqEsc($u['created_at'])?></small></div><?php endforeach;?></div></section></main></body></html>
