<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
$token=trim((string)($_GET['token']??''));
if($token===''||strlen($token)>128){http_response_code(404);exit('Asset not found.');}
$stmt=$conn->prepare('SELECT a.*,p.property_name,p.property_code,p.company_name,p.logo_path,p.primary_color,p.secondary_color FROM assets a INNER JOIN cpms_properties p ON p.id=a.property_id WHERE a.public_token=? AND p.is_active=1 LIMIT 1');
if(!$stmt){http_response_code(500);exit('Unable to load asset.');}$stmt->bind_param('s',$token);$stmt->execute();$asset=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$asset){http_response_code(404);exit('Asset not found.');}
$history=[];$stmt=$conn->prepare('SELECT event_type,event_notes,changed_by,created_at FROM asset_history WHERE asset_id=? AND property_id=? ORDER BY created_at DESC,id DESC LIMIT 10');if($stmt){$stmt->bind_param('ii',$asset['id'],$asset['property_id']);$stmt->execute();$r=$stmt->get_result();while($x=$r->fetch_assoc())$history[]=$x;$stmt->close();}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$primary=preg_match('/^#[0-9a-fA-F]{6}$/',(string)$asset['primary_color'])?$asset['primary_color']:'#0f172a';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo e($asset['asset_name']);?></title><style>:root{--primary:<?php echo e($primary);?>}*{box-sizing:border-box}body{margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#0f172a}.hero{background:var(--primary);color:#fff;padding:28px 18px}.wrap{max-width:760px;margin:auto}.card{background:#fff;border-radius:16px;padding:20px;margin:16px;box-shadow:0 8px 25px rgba(15,23,42,.08)}.badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#e2e8f0;font-weight:700}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.item{padding:12px;border:1px solid #e2e8f0;border-radius:10px}.item span{display:block;color:#64748b;font-size:12px;margin-bottom:4px}.photo{width:100%;max-height:340px;object-fit:cover;border-radius:12px}.history{border-left:3px solid #cbd5e1;padding-left:12px;margin:14px 0}.history small{color:#64748b}@media(max-width:560px){.grid{grid-template-columns:1fr}}</style></head><body><div class="hero"><div class="wrap"><small><?php echo e($asset['property_name']);?></small><h1><?php echo e($asset['asset_name']);?></h1><strong><?php echo e($asset['asset_code']);?></strong></div></div><main class="wrap"><div class="card"><?php if(!empty($asset['photo_path'])):?><img class="photo" src="<?php echo e($asset['photo_path']);?>" alt="Asset photo"><?php endif;?><p><span class="badge"><?php echo e($asset['condition_rating']);?></span> <span class="badge"><?php echo e($asset['asset_status']);?></span></p><div class="grid"><?php foreach(['asset_category'=>'Category','location'=>'Location','block_location'=>'Block / Zone','brand'=>'Brand','model'=>'Model','serial_number'=>'Serial Number','installation_date'=>'Installation Date','warranty_expiry'=>'Warranty Expiry','maintenance_frequency'=>'Maintenance Frequency','next_service_date'=>'Next Service'] as $k=>$label):?><div class="item"><span><?php echo $label;?></span><strong><?php echo e($asset[$k]?:'-');?></strong></div><?php endforeach;?></div></div><div class="card"><h2>Maintenance Timeline</h2><?php foreach($history as $h):?><div class="history"><strong><?php echo e($h['event_type']);?></strong><p><?php echo e($h['event_notes']);?></p><small><?php echo e($h['created_at']);?></small></div><?php endforeach;?><?php if(!$history):?><p>No maintenance history available.</p><?php endif;?></div></main></body></html>
