<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
cpmsPropertyRequire('assets.manage');
require_once dirname(__DIR__).'/includes/asset_service.php';
if(!cpmsAssetSchemaReady($conn)) exit('Import asset_bci_sprint_2_7.sql first.');
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
    $name=trim((string)($_POST['asset_name']??''));$cat=trim((string)($_POST['asset_category']??''));$loc=trim((string)($_POST['location']??''));
    if($name===''||$cat===''||$loc==='')$errors[]='Asset name, category and location are required.';
    if(!$errors){
        $code=cpmsAssetGenerateCode($conn,$currentPropertyId);$token=bin2hex(random_bytes(24));
        $block=trim((string)($_POST['block_location']??''));$brand=trim((string)($_POST['brand']??''));$model=trim((string)($_POST['model']??''));$serial=trim((string)($_POST['serial_number']??''));$purchase=trim((string)($_POST['purchase_date']??''));$cost=(float)($_POST['purchase_cost']??0);$install=trim((string)($_POST['installation_date']??''));$warranty=trim((string)($_POST['warranty_expiry']??''));$vendor=trim((string)($_POST['vendor_name']??''));$phone=trim((string)($_POST['vendor_phone']??''));$freq=(string)($_POST['maintenance_frequency']??'Monthly');$next=trim((string)($_POST['next_service_date']??''));$status=(string)($_POST['asset_status']??'Active');$condition=(string)($_POST['condition_rating']??'Good');$notes=trim((string)($_POST['notes']??''));$created=(string)$propertyPortalUser['full_name'];$photoPath='';
        if(isset($_FILES['photo'])&&(int)$_FILES['photo']['error']===UPLOAD_ERR_OK){$f=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$f->file($_FILES['photo']['tmp_name']);$map=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($map[$mime]))$errors[]='Photo must be JPG, PNG or WebP.';elseif((int)$_FILES['photo']['size']>5*1024*1024)$errors[]='Photo maximum size is 5 MB.';else{$dir=__DIR__.'/uploads/assets/property_'.$currentPropertyId;if(!is_dir($dir))mkdir($dir,0755,true);$fn=bin2hex(random_bytes(12)).'.'.$map[$mime];if(move_uploaded_file($_FILES['photo']['tmp_name'],$dir.'/'.$fn))$photoPath='uploads/assets/property_'.$currentPropertyId.'/'.$fn;}}
        if(!$errors){$stmt=$conn->prepare('INSERT INTO assets(property_id,asset_code,public_token,asset_name,asset_category,location,block_location,brand,model,serial_number,purchase_date,purchase_cost,installation_date,warranty_expiry,vendor_name,vendor_phone,maintenance_frequency,next_service_date,asset_status,condition_rating,notes,photo_path,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,NULLIF(?,""),NULLIF(?,0),NULLIF(?,""),NULLIF(?,""),NULLIF(?,""),NULLIF(?,""),?,NULLIF(?,""),?,?,?,?,NULLIF(?,""),?)');
        if(!$stmt)$errors[]='Unable to prepare asset record.';else{$stmt->bind_param('isssssssssdssssssssssss',$currentPropertyId,$code,$token,$name,$cat,$loc,$block,$brand,$model,$serial,$purchase,$cost,$install,$warranty,$vendor,$phone,$freq,$next,$status,$condition,$notes,$photoPath,$created);if($stmt->execute()){$id=(int)$stmt->insert_id;$stmt->close();cpmsAssetHistoryAdd($conn,$id,$currentPropertyId,'Created','Asset registered.',$created);header('Location: asset_view.php?id='.$id);exit;}else{$errors[]='Unable to create asset: '.$stmt->error;$stmt->close();}}}
    }
}
$pageTitle='Add Asset';$activeMenu='assets';require __DIR__.'/includes/layout_header.php';require __DIR__.'/includes/layout_sidebar.php';require __DIR__.'/includes/layout_topbar.php';?>
<link rel="stylesheet" href="assets/asset-register.css"><section class="page-heading"><div><span class="section-label">ASSET MANAGEMENT</span><h1>Add Asset</h1><p>Create a property-scoped asset record.</p></div></section><?php foreach($errors as $e):?><div class="alert-error"><?php echo propertyPortalEscape($e);?></div><?php endforeach;?><form method="post" enctype="multipart/form-data" class="panel asset-form"><div class="form-grid"><?php $fields=['asset_name'=>'Asset Name *','asset_category'=>'Category *','location'=>'Location *','block_location'=>'Block / Zone','brand'=>'Brand','model'=>'Model','serial_number'=>'Serial Number','purchase_date'=>'Purchase Date','purchase_cost'=>'Purchase Cost (RM)','installation_date'=>'Installation Date','warranty_expiry'=>'Warranty Expiry','vendor_name'=>'Vendor','vendor_phone'=>'Vendor Phone','next_service_date'=>'Next Service Date'];foreach($fields as $n=>$l):?><div class="field-group"><label><?php echo $l;?></label><input <?php echo strpos($n,'date')!==false||$n==='warranty_expiry'?'type="date"':'';?> <?php echo $n==='purchase_cost'?'type="number" step="0.01"':'';?> name="<?php echo $n;?>" value="<?php echo propertyPortalEscape((string)($_POST[$n]??''));?>"></div><?php endforeach;?><div class="field-group"><label>Maintenance Frequency</label><select name="maintenance_frequency"><?php foreach(['Weekly','Monthly','Quarterly','Half Yearly','Yearly','As Required'] as $o):?><option><?php echo $o;?></option><?php endforeach;?></select></div><div class="field-group"><label>Asset Status</label><select name="asset_status"><?php foreach(['Active','Under Maintenance','Out of Service','Expired','Disposed'] as $o):?><option><?php echo $o;?></option><?php endforeach;?></select></div><div class="field-group"><label>Condition</label><select name="condition_rating"><?php foreach(['Excellent','Good','Fair','Poor','Critical'] as $o):?><option><?php echo $o;?></option><?php endforeach;?></select></div><div class="field-group"><label>Asset Photo</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></div></div><div class="field-group"><label>Notes</label><textarea name="notes" rows="4"><?php echo propertyPortalEscape((string)($_POST['notes']??''));?></textarea></div><button class="button button-primary">Save Asset</button><a class="button button-secondary" href="assets.php">Cancel</a></form><?php require __DIR__.'/includes/layout_footer.php';?>
