<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
require_once dirname(__DIR__) . '/includes/compliance_service.php';
cpmsRequire('compliance.view', $conn);
if (!isset($propertyPortalUser) || !is_array($propertyPortalUser)) { $propertyPortalUser=[]; }
$propertyId=cpmsCompliancePropertyId($propertyPortalUser);$id=(int)($_GET['id']??0);
if ($propertyId<1||$id<1) { http_response_code(400); exit('Invalid request.'); }
$record=cpmsComplianceFind($conn,$propertyId,$id);if(!$record){http_response_code(404);exit('Compliance item not found.');}
$history=cpmsComplianceHistory($conn,$propertyId,$id);$pageTitle='Compliance Details';$activeMenu='compliance';require __DIR__.'/includes/layout_header.php';require __DIR__.'/includes/layout_sidebar.php';require __DIR__.'/includes/layout_topbar.php';
?>
<link rel="stylesheet" href="assets/compliance-module.css"><div class="compliance-wrap"><div class="compliance-head"><div><span class="compliance-eyebrow">COMPLIANCE MANAGEMENT</span><h1><?php echo cpmsComplianceEscape($record['title']);?></h1><p><?php echo cpmsComplianceEscape($record['category']);?> · <?php echo cpmsComplianceEscape($record['location']);?></p></div><div class="compliance-actions"><a class="compliance-btn compliance-btn-secondary" href="compliance.php">Back</a><?php if($record['status']==='active'&&cpmsCan('compliance.update',$conn)):?><a class="compliance-btn compliance-btn-primary" href="compliance_complete.php?id=<?php echo $id;?>">Mark Completed</a><?php endif;?></div></div><div class="compliance-form"><div class="compliance-row"><div><strong>Frequency</strong><p><?php echo cpmsComplianceEscape(str_replace('_',' ',(string)$record['frequency_type']));?></p></div><div><strong>Next Due Date</strong><p><?php echo cpmsComplianceEscape(date('d/m/Y',strtotime((string)$record['next_due_date'])));?></p></div></div><div class="compliance-row"><div><strong>Responsible Person</strong><p><?php echo cpmsComplianceEscape($record['responsible_person']);?></p></div><div><strong>Status</strong><p><?php echo cpmsComplianceEscape($record['status']);?></p></div></div><strong>Notes</strong><p><?php echo nl2br(cpmsComplianceEscape($record['notes']));?></p></div><div class="compliance-panel" style="margin-top:18px"><div class="compliance-panel-head"><strong>Completion History</strong><span><?php echo count($history);?> record(s)</span></div><?php if(!$history):?><div class="compliance-empty">No completion record yet.</div><?php else:?><div class="compliance-table-wrap"><table class="compliance-table"><thead><tr><th>Completed</th><th>Result</th><th>Remarks</th><th>Completed By</th><th>Next Due</th></tr></thead><tbody><?php foreach($history as $h):?><tr><td><?php echo cpmsComplianceEscape(date('d/m/Y',strtotime((string)$h['completed_date'])));?></td><td><?php echo cpmsComplianceEscape($h['result']);?></td><td><?php echo cpmsComplianceEscape($h['remarks']);?></td><td><?php echo cpmsComplianceEscape($h['completed_by_name']);?></td><td><?php echo $h['next_due_date']?cpmsComplianceEscape(date('d/m/Y',strtotime((string)$h['next_due_date']))):'-';?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></div><?php require __DIR__.'/includes/layout_footer.php';?>
