<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
require_once dirname(__DIR__) . '/includes/compliance_service.php';
cpmsRequire('compliance.update', $conn);
if (!isset($propertyPortalUser) || !is_array($propertyPortalUser)) { $propertyPortalUser=[]; }
$propertyId=cpmsCompliancePropertyId($propertyPortalUser);$id=(int)($_GET['id']??$_POST['id']??0);
if ($propertyId<1||$id<1) { http_response_code(400); exit('Invalid request.'); }
$record=cpmsComplianceFind($conn,$propertyId,$id);if(!$record){http_response_code(404);exit('Compliance item not found.');}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!cpmsComplianceVerifyCsrf($_POST['csrf_token']??null)){$errors[]='Invalid security token.';}
 $completedDate=trim((string)($_POST['completed_date']??date('Y-m-d')));$result=trim((string)($_POST['result']??'Compliant'));$remarks=trim((string)($_POST['remarks']??''));$inspectionId=(int)($_POST['inspection_id']??0);
 if(!in_array($result,['Compliant','Non-Compliant','Observation'],true)){$result='Compliant';}
 if(!$errors){$next=cpmsComplianceNextDueDate($completedDate,(string)$record['frequency_type']);$uid=cpmsComplianceUserId($propertyPortalUser);$uname=cpmsComplianceUserName($propertyPortalUser);$conn->begin_transaction();try{$stmt=$conn->prepare('INSERT INTO compliance_completion_history(schedule_id,property_id,completed_date,previous_due_date,next_due_date,result,remarks,inspection_id,completed_by_id,completed_by_name) VALUES(?,?,?,?,NULLIF(?,""),?,?,NULLIF(?,0),NULLIF(?,0),?)');if(!$stmt)throw new RuntimeException('Unable to prepare completion record.');$nextValue=(string)$next;$stmt->bind_param('iisssssiiis',$id,$propertyId,$completedDate,$record['next_due_date'],$nextValue,$result,$remarks,$inspectionId,$uid,$uname);if(!$stmt->execute())throw new RuntimeException($stmt->error);$stmt->close();if($next===null){$update=$conn->prepare('UPDATE compliance_schedules SET status="inactive" WHERE id=? AND property_id=?');$update->bind_param('ii',$id,$propertyId);}else{$update=$conn->prepare('UPDATE compliance_schedules SET next_due_date=? WHERE id=? AND property_id=?');$update->bind_param('sii',$next,$id,$propertyId);}if(!$update->execute())throw new RuntimeException($update->error);$update->close();$conn->commit();header('Location: compliance_view.php?id='.$id);exit;}catch(Throwable $e){$conn->rollback();$errors[]='Unable to complete compliance item: '.$e->getMessage();}}
}
$pageTitle='Complete Compliance Item';$activeMenu='compliance';require __DIR__.'/includes/layout_header.php';require __DIR__.'/includes/layout_sidebar.php';require __DIR__.'/includes/layout_topbar.php';
?>
<link rel="stylesheet" href="assets/compliance-module.css"><div class="compliance-wrap"><div class="compliance-head"><div><span class="compliance-eyebrow">COMPLIANCE MANAGEMENT</span><h1>Mark Completed</h1><p><?php echo cpmsComplianceEscape($record['title']);?></p></div><a class="compliance-btn compliance-btn-secondary" href="compliance_view.php?id=<?php echo $id;?>">Back</a></div><?php foreach($errors as $e):?><div class="compliance-alert compliance-alert-error"><?php echo cpmsComplianceEscape($e);?></div><?php endforeach;?><form method="post" class="compliance-form"><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="csrf_token" value="<?php echo cpmsComplianceEscape(cpmsComplianceCsrfToken());?>"><div class="compliance-row"><div class="compliance-field"><label>Completed Date</label><input type="date" name="completed_date" value="<?php echo date('Y-m-d');?>" required></div><div class="compliance-field"><label>Result</label><select name="result"><option>Compliant</option><option>Non-Compliant</option><option>Observation</option></select></div></div><div class="compliance-field"><label>Inspection ID (optional)</label><input type="number" min="1" name="inspection_id" placeholder="Link to an existing inspection record"></div><div class="compliance-field"><label>Remarks</label><textarea name="remarks" rows="5"></textarea></div><button class="compliance-btn compliance-btn-primary">Confirm Completion</button></form></div><?php require __DIR__.'/includes/layout_footer.php';?>
