<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
cpmsPropertyRequire('assets.view');
require_once dirname(__DIR__) . '/includes/pm_service.php';
if (!cpmsPmSchemaReady($conn)) exit('Preventive Maintenance migration not imported. Import cpms/sql/preventive_maintenance_sprint_2_9.sql first.');
$id=(int)($_GET['id']??$_POST['id']??0); $errors=[]; $row=null;
if($id>0){$s=$conn->prepare('SELECT * FROM pm_schedules WHERE id=? AND property_id=? LIMIT 1');if($s){$s->bind_param('ii',$id,$currentPropertyId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();}if(!$row)exit('PM schedule not found.');}
$assets=[];$s=$conn->prepare("SELECT id,asset_code,asset_name FROM assets WHERE property_id=? AND asset_status<>'Disposed' ORDER BY asset_name");if($s){$s->bind_param('i',$currentPropertyId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$assets[]=$x;$s->close();}
$staff=[];$s=$conn->prepare("SELECT id,full_name FROM staff WHERE property_id=? AND account_status='Active' ORDER BY full_name");if($s){$s->bind_param('i',$currentPropertyId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$staff[]=$x;$s->close();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!propertyPortalVerifyCsrf(is_string($_POST['csrf_token']??null)?$_POST['csrf_token']:null))$errors[]='Invalid request token.';
 $assetId=(int)($_POST['asset_id']??0);$title=trim((string)($_POST['task_title']??''));$desc=trim((string)($_POST['task_description']??''));$unit=(string)($_POST['frequency_unit']??'Month');$value=max(1,(int)($_POST['frequency_value']??1));$priority=(string)($_POST['priority']??'Medium');$staffId=(int)($_POST['assigned_staff_id']??0);$cost=(float)($_POST['estimated_cost']??0);$start=(string)($_POST['start_date']??'');$next=(string)($_POST['next_due_date']??'');$active=isset($_POST['is_active'])?1:0;
 if($assetId<1)$errors[]='Please select an asset.'; if($title==='')$errors[]='Task title is required.'; if($start===''||$next==='')$errors[]='Start date and next due date are required.';
 if(!$errors){$user=(string)$propertyPortalUser['full_name']; if($id>0){$q=$conn->prepare('UPDATE pm_schedules SET asset_id=?,task_title=?,task_description=?,frequency_unit=?,frequency_value=?,priority=?,assigned_staff_id=NULLIF(?,0),estimated_cost=NULLIF(?,0),start_date=?,next_due_date=?,is_active=? WHERE id=? AND property_id=?');$q->bind_param('isssisidssiii',$assetId,$title,$desc,$unit,$value,$priority,$staffId,$cost,$start,$next,$active,$id,$currentPropertyId);}else{$q=$conn->prepare('INSERT INTO pm_schedules(property_id,asset_id,task_title,task_description,frequency_unit,frequency_value,priority,assigned_staff_id,estimated_cost,start_date,next_due_date,is_active,created_by) VALUES(?,?,?,?,?,?,?,NULLIF(?,0),NULLIF(?,0),?,?,?,?,?)');$q->bind_param('iisssisidssiss',$currentPropertyId,$assetId,$title,$desc,$unit,$value,$priority,$staffId,$cost,$start,$next,$active,$user);}if($q&&$q->execute()){$_SESSION['pm_flash']=['type'=>'success','message'=>$id>0?'PM schedule updated.':'PM schedule created.'];$q->close();header('Location: preventive_maintenance.php');exit;} $errors[]='Unable to save PM schedule.';}
 $row=$_POST;
}
$pageTitle=$id>0?'Edit PM Schedule':'Add PM Schedule';$activeMenu='preventive_maintenance';require __DIR__.'/includes/layout_header.php';require __DIR__.'/includes/layout_sidebar.php';require __DIR__.'/includes/layout_topbar.php';
function pmv($row,$key,$fallback=''){return propertyPortalEscape((string)($row[$key]??$fallback));}
?>
<link rel="stylesheet" href="assets/preventive-maintenance.css"><section class="page-heading"><div><span class="section-label">PREVENTIVE MAINTENANCE</span><h1><?php echo $id>0?'Edit PM Schedule':'Add PM Schedule';?></h1><p>Define a recurring task for an asset.</p></div></section>
<?php foreach($errors as $e):?><div class="pm-alert danger"><?php echo propertyPortalEscape($e);?></div><?php endforeach;?>
<section class="panel"><form method="post" class="pm-form"><input type="hidden" name="csrf_token" value="<?php echo propertyPortalEscape(propertyPortalCsrfToken());?>"><input type="hidden" name="id" value="<?php echo $id;?>"><div><label>Asset *</label><select name="asset_id" required><option value="">Select asset</option><?php foreach($assets as $a):?><option value="<?php echo (int)$a['id'];?>" <?php echo (int)($row['asset_id']??0)===(int)$a['id']?'selected':'';?>><?php echo propertyPortalEscape($a['asset_code'].' - '.$a['asset_name']);?></option><?php endforeach;?></select></div><div><label>Task Title *</label><input name="task_title" value="<?php echo pmv($row,'task_title');?>" required></div><div class="full"><label>Description</label><textarea name="task_description" rows="4"><?php echo pmv($row,'task_description');?></textarea></div><div><label>Frequency</label><div class="pm-inline"><input type="number" min="1" name="frequency_value" value="<?php echo pmv($row,'frequency_value','1');?>"><select name="frequency_unit"><?php foreach(['Day','Week','Month','Year'] as $u):?><option <?php echo ($row['frequency_unit']??'Month')===$u?'selected':'';?>><?php echo $u;?></option><?php endforeach;?></select></div></div><div><label>Priority</label><select name="priority"><?php foreach(['Low','Medium','High','Emergency'] as $p):?><option <?php echo ($row['priority']??'Medium')===$p?'selected':'';?>><?php echo $p;?></option><?php endforeach;?></select></div><div><label>Assigned Staff</label><select name="assigned_staff_id"><option value="0">Unassigned</option><?php foreach($staff as $s):?><option value="<?php echo (int)$s['id'];?>" <?php echo (int)($row['assigned_staff_id']??0)===(int)$s['id']?'selected':'';?>><?php echo propertyPortalEscape((string)$s['full_name']);?></option><?php endforeach;?></select></div><div><label>Estimated Cost (RM)</label><input type="number" step="0.01" min="0" name="estimated_cost" value="<?php echo pmv($row,'estimated_cost');?>"></div><div><label>Start Date *</label><input type="date" name="start_date" value="<?php echo pmv($row,'start_date',date('Y-m-d'));?>" required></div><div><label>Next Due Date *</label><input type="date" name="next_due_date" value="<?php echo pmv($row,'next_due_date',date('Y-m-d'));?>" required></div><div class="full"><label class="check"><input type="checkbox" name="is_active" value="1" <?php echo !isset($row['is_active'])||(int)$row['is_active']===1?'checked':'';?>> Active schedule</label></div><div class="full pm-actions"><button class="button button-primary">Save Schedule</button><a class="button button-secondary" href="preventive_maintenance.php">Cancel</a></div></form></section><?php require __DIR__.'/includes/layout_footer.php';?>
